/*********************************************************************//**
\file       test_pgn_enable_sweep.cpp
\author     (Created) Claude Code
\date       (Created) 06/08/2026
\brief      DB-driven two-device sweep of the Rx/Tx PGN enable filters.
\details    Consolidates and supersedes the earlier hand-curated Tx-blocking
            sweeps (single-frame and fast-packet standard PGNs). Every fact
            that used to live in hard-coded tables — which PGNs exist, their
            payload lengths, where the SID and instance bytes sit, which are
            fast-packet — now arrives from a runtime manifest generated by an
            internal tool from the NMEA 2000 PGN database (see
            tests/support/pgn_manifest.hpp for the manifest contract and why
            the data cannot live in this repository).

            The proprietary-range sweeps are intentionally untouched: that
            space is not enumerable from the PGN database and stays covered
            by the dedicated proprietary tests.

            ----------------------------------------------------------------
            Rig
            ----------------------------------------------------------------
            Two gateways ("device A" and "device B") on one shared N2K bus,
            described by a rig config JSON outside this repository
            (tests/support/rig_config.hpp). The sweep probes each device's
            product information and asserts the reported model matches the
            rig's expectation before configuring anything, so a re-plugged
            port fails loudly instead of sweeping the wrong device.

            ----------------------------------------------------------------
            Sweep matrix
            ----------------------------------------------------------------
            Four sweeps, each its own TEST_F so operating-mode changes happen
            once per sweep rather than once per PGN:

              Tx-filter sweep (per direction):
                transmitter in Normal mode (Tx enable list gates host-Tx),
                counterpart in Rx-All mode as a transparent bus monitor.
                Toggle the transmitter's Tx enable for each PGN and assert
                host-Tx traffic appears/disappears at the monitor.

              Rx-filter sweep (per direction):
                transmitter in Normal mode with the PGN Tx-enabled (traffic
                source), receiver in Normal mode with its Rx enable toggled.
                Assert bus traffic reaches/stops-reaching the receiver's
                host output.

            Each PGN leaves a classified verdict record (see Verdict); the
            two-phase structure is self-checking — a PGN must be observed
            while enabled before "not observed while disabled" is allowed to
            count as a pass, so a transmitter failure cannot masquerade as a
            filter success. A payload-length problem classifies as a skip,
            never as a filter failure.

            ----------------------------------------------------------------
            Environment variables
            ----------------------------------------------------------------
              ACTISENSE_TEST_RIG           Path to the rig config JSON
                                           (required unless the legacy port
                                           variables below are set).
              ACTISENSE_TEST_FIXTURE       Fixture id to run (default: the
                                           rig's first fixture).
              ACTISENSE_TEST_PGN_MANIFEST  Path to the PGN manifest JSON
                                           (required; absent => SKIP).
              ACTISENSE_TEST_PORT          Override device A's serial port
                                           (legacy; with RX_PORT, also works
                                           with no rig file at all).
              ACTISENSE_TEST_RX_PORT       Override device B's serial port.
              ACTISENSE_TEST_BAUD          Override baud for both ports.
              ACTISENSE_TEST_FULL_SWEEP    "1" => sweep every manifest PGN;
                                           default is a deterministic smoke
                                           subset (see selectSweepCandidates).
              ACTISENSE_TEST_ONLY_PGN      Restrict the sweep to one PGN.
              ACTISENSE_TEST_WIRE_TRACE    "1" => hex-trace both sessions.
              ACTISENSE_TEST_RX_DEBUG      "1" => dump every captured frame.

            ----------------------------------------------------------------
            State restoration policy
            ----------------------------------------------------------------
            SetUp saves each gateway's starting OperatingMode; TearDown
            restores it (best-effort), and restores the operating-mode
            default Rx+Tx enable lists on both devices to discard the
            sweep's session-only mutations. No EEPROM/FLASH commit is ever
            issued, so a clean run leaves no persistent drift.

\copyright  <h2>&copy; COPYRIGHT 2026 Active Research Limited<br>ALL RIGHTS RESERVED</h2>
*******************************************************************************/

/* Dependent includes ------------------------------------------------------- */
#include "public/api.hpp"
#include "public/received_frame.hpp"

#include "../support/pgn_manifest.hpp"
#include "../support/pgn_sweep_report.hpp"
#include "../support/rig_config.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <cctype>
#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <deque>
#include <future>
#include <iostream>
#include <mutex>
#include <optional>
#include <span>
#include <string>
#include <thread>
#include <unordered_set>
#include <vector>

namespace Actisense
{
namespace Sdk
{
namespace Test
{

/* Constants ---------------------------------------------------------------- */

static constexpr auto kDefaultTimeout = std::chrono::milliseconds(3000);
static constexpr auto kSetupDelay = std::chrono::milliseconds(500);
static constexpr auto kSettleDelay = std::chrono::milliseconds(300);
static constexpr auto kRxWaitTimeout = std::chrono::milliseconds(1500);
static constexpr auto kRxWaitTimeoutFast = std::chrono::milliseconds(2500);
static constexpr auto kModeChangeSettle = std::chrono::milliseconds(1500);
static constexpr std::size_t kMaxCapturedFrames = 4096;

/* PGNs excluded for firmware-behaviour reasons (not DB facts):
     126208  NMEA Group Function — control PGN, has its own handling
     126464  PGN List — control PGN, has its own handling
     126993  Heartbeat — firmware-emitted, bypasses the Tx-enable filter
     127508  Battery Status — gateways carry no battery; firmware refuses
             host-Tx of this PGN outright */
static const std::unordered_set<uint32_t> kSkipPgns = {
	126208,
	126464,
	126993,
	127508,
};

/* Verdict taxonomy, SweepRecord and the report artifacts live in
   tests/support/pgn_sweep_report.hpp, shared with the hermetic unit tests. */

/* Captured receive frame (owning copy of the event's payload view). */
struct CapturedFrame
{
	uint32_t pgn = 0;
	uint8_t source = 0xFF;
	std::vector<uint8_t> data;
};

/* Test Fixture ------------------------------------------------------------- */

class PgnEnableSweepTest : public ::testing::Test
{
protected:
	/* One rig endpoint: a public Session plus its capture queue. */
	struct Endpoint
	{
		RigDevice config;
		std::unique_ptr<Session> session;
		std::string probedModel;
		std::optional<OperatingMode> savedMode;
		bool listsTouched = false;

		std::mutex mutex;
		std::condition_variable cv;
		std::deque<CapturedFrame> frames;
	};

	RigFixture fixture_;
	Endpoint endpointA_;
	Endpoint endpointB_;
	PgnManifest manifest_;
	uint32_t runSalt_ = 0;
	bool debugRxDump_ = false;
	std::vector<SweepRecord> records_;

	void SetUp() override
	{
		resolveFixture();
		if (::testing::Test::IsSkipped() || ::testing::Test::HasFailure()) {
			return;
		}

		const auto manifestPath = manifestPathFromEnv();
		if (!manifestPath.has_value()) {
			GTEST_SKIP() << "ACTISENSE_TEST_PGN_MANIFEST not set - the sweep is"
						 << " manifest-driven and cannot run without it";
		}
		std::string error;
		auto manifest = loadPgnManifest(*manifestPath, error);
		ASSERT_TRUE(manifest.has_value()) << "Manifest load failed: " << error;
		manifest_ = std::move(*manifest);
		std::cout << "  Manifest: " << manifest_.entries.size() << " PGNs, lib version "
				  << manifest_.n2kLibVersion << ", generated " << manifest_.generated
				  << std::endl;

		runSalt_ = static_cast<uint32_t>(
			std::chrono::steady_clock::now().time_since_epoch().count() & 0xFFFFFFFFu);
		if (const char* dbg = std::getenv("ACTISENSE_TEST_RX_DEBUG");
			dbg && std::string(dbg) == "1") {
			debugRxDump_ = true;
		}

		endpointA_.config = fixture_.deviceA;
		endpointB_.config = fixture_.deviceB;
		openEndpoint(endpointA_, "A");
		openEndpoint(endpointB_, "B");
		if (::testing::Test::HasFatalFailure()) {
			return;
		}
		std::this_thread::sleep_for(kSetupDelay);

		verifyModel(endpointA_, "device A");
		verifyModel(endpointB_, "device B");
	}

	void TearDown() override
	{
		restoreEndpoint(endpointA_);
		restoreEndpoint(endpointB_);
		if (endpointA_.session) { endpointA_.session->close(); }
		if (endpointB_.session) { endpointB_.session->close(); }
		printSummary();
		writeArtifacts();
	}

	/* Merge this sweep's records into the on-disk scorecard and regenerate
	   the Markdown report (ACTISENSE_TEST_REPORT_DIR, default: cwd). */
	void writeArtifacts()
	{
		if (records_.empty()) {
			return;
		}
		SweepReportMeta meta;
		meta.n2kLibVersion = manifest_.n2kLibVersion;
		meta.manifestGenerated = manifest_.generated;
		const std::string directory = reportDir();
		if (!updateSweepArtifacts(directory, meta, records_)) {
			ADD_FAILURE() << "Failed to write sweep artifacts to '" << directory << "'";
			return;
		}
		std::cout << "  Scorecard + report updated in '" << directory << "'" << std::endl;
	}

	/* Rig/environment resolution ------------------------------------------- */

	void resolveFixture()
	{
		const auto rigPath = rigPathFromEnv();
		const char* portEnv = std::getenv("ACTISENSE_TEST_PORT");
		const char* rxPortEnv = std::getenv("ACTISENSE_TEST_RX_PORT");

		if (rigPath.has_value()) {
			std::string error;
			auto rig = loadRigConfig(*rigPath, error);
			/* A configured-but-unusable rig is a hard failure, not a skip - a
			   bench that thinks it is sweeping must not silently do nothing. */
			ASSERT_TRUE(rig.has_value()) << "Rig config load failed: " << error;
			const RigFixture* fixture = selectFixture(*rig);
			ASSERT_NE(fixture, nullptr) << "ACTISENSE_TEST_FIXTURE names a fixture"
										<< " the rig config does not define";
			fixture_ = *fixture;
		} else if (portEnv && *portEnv && rxPortEnv && *rxPortEnv) {
			/* Legacy ad-hoc rig from environment variables only: no model
			   assertion, no device quirks. */
			fixture_.id = "env";
			fixture_.deviceA.port = portEnv;
			fixture_.deviceB.port = rxPortEnv;
		} else {
			GTEST_SKIP() << "No rig configured - set ACTISENSE_TEST_RIG (or the"
						 << " legacy ACTISENSE_TEST_PORT + ACTISENSE_TEST_RX_PORT)"
						 << " to run the hardware sweep";
		}

		/* Environment overrides for ad-hoc runs against a different bench. */
		if (portEnv && *portEnv) {
			fixture_.deviceA.port = portEnv;
		}
		if (rxPortEnv && *rxPortEnv) {
			fixture_.deviceB.port = rxPortEnv;
		}
		if (const char* baud = std::getenv("ACTISENSE_TEST_BAUD"); baud && *baud) {
			const uint32_t parsed = static_cast<uint32_t>(std::strtoul(baud, nullptr, 10));
			fixture_.deviceA.baud = parsed;
			fixture_.deviceB.baud = parsed;
		}
		if (fixture_.deviceA.port == fixture_.deviceB.port) {
			GTEST_SKIP() << "device A and device B resolve to the same serial port -"
						 << " the sweep needs two physical devices";
		}
		std::cout << "  Fixture '" << fixture_.id << "': A=" << fixture_.deviceA.port
				  << " B=" << fixture_.deviceB.port << std::endl;
	}

	void openEndpoint(Endpoint& endpoint, const char* label)
	{
		SerialConfig config;
		config.port = endpoint.config.port;
		config.baud = endpoint.config.baud;
		endpoint.session = Api::createSerialSession(
			config,
			[this, &endpoint](const EventVariant& event) { handleEvent(endpoint, event); },
			[label](ErrorCode code, std::string_view message) {
				std::cerr << "Session " << label << " error: " << static_cast<int>(code)
						  << " - " << message << std::endl;
			});
		ASSERT_NE(endpoint.session, nullptr)
			<< "Failed to open session on " << endpoint.config.port;

		if (const char* trace = std::getenv("ACTISENSE_TEST_WIRE_TRACE");
			trace && std::string(trace) == "1") {
			WireTraceConfig traceConfig;
			traceConfig.format = WireTraceFormat::Hex;
			traceConfig.bytesPerLine = 16;
			traceConfig.includeAscii = true;
			const std::string prefix = std::string("[") + label + "] ";
			endpoint.session->setWireTrace(traceConfig, [prefix](std::string_view line) {
				std::cerr << prefix << line;
			});
		}
	}

	void handleEvent(Endpoint& endpoint, const EventVariant& event)
	{
		const auto* message = std::get_if<ParsedMessageEvent>(&event);
		if (message == nullptr) {
			return;
		}
		const auto frame = asReceivedFrame(*message);
		if (!frame.has_value()) {
			return;
		}
		CapturedFrame captured;
		captured.pgn = frame->pgn;
		captured.source = frame->source;
		captured.data.assign(frame->data.begin(), frame->data.end());

		if (debugRxDump_) {
			std::cout << "    [" << (&endpoint == &endpointA_ ? 'A' : 'B')
					  << "] src=" << static_cast<int>(captured.source)
					  << " PGN=" << captured.pgn << " len=" << captured.data.size()
					  << std::endl;
		}

		{
			std::lock_guard<std::mutex> lock(endpoint.mutex);
			endpoint.frames.push_back(std::move(captured));
			/* Both endpoints capture, but only the current observer is ever
			   drained - bound the queue so a long full sweep on a chatty bus
			   cannot grow the transmitter side without limit. */
			while (endpoint.frames.size() > kMaxCapturedFrames) {
				endpoint.frames.pop_front();
			}
		}
		endpoint.cv.notify_one();
	}

	/* Probe the device's product information and assert the reported model
	   matches the rig's expectation (case-insensitive substring). */
	void verifyModel(Endpoint& endpoint, const char* label)
	{
		std::promise<std::optional<HardwareInfo>> promise;
		auto future = promise.get_future();
		endpoint.session->getHardwareInfo(
			kDefaultTimeout,
			[&promise](ErrorCode code, std::string_view, const std::optional<HardwareInfo>& info,
					   ResponseOrigin) {
				promise.set_value(code == ErrorCode::Ok ? info : std::nullopt);
			});
		const auto info = future.get();
		if (!info.has_value()) {
			if (endpoint.config.expectedModel.empty()) {
				std::cout << "  " << label << " on " << endpoint.config.port
						  << ": model probe failed (no expectation configured -"
						  << " continuing)" << std::endl;
				return;
			}
			FAIL() << label << " on " << endpoint.config.port
				   << " did not answer the product-information probe - check the rig";
		}
		endpoint.probedModel = info->modelId;
		std::cout << "  " << label << " on " << endpoint.config.port << ": model '"
				  << endpoint.probedModel << "'" << std::endl;

		if (endpoint.config.expectedModel.empty()) {
			return;
		}
		const auto lower = [](std::string s) {
			std::transform(s.begin(), s.end(), s.begin(),
						   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
			return s;
		};
		const std::string probed = lower(endpoint.probedModel);
		const std::string expected = lower(endpoint.config.expectedModel);
		ASSERT_NE(probed.find(expected), std::string::npos)
			<< label << " on " << endpoint.config.port << " reports model '"
			<< endpoint.probedModel << "' but the rig config expects '"
			<< endpoint.config.expectedModel
			<< "' - refusing to sweep a mismatched device (re-plugged port?)";
	}

	/* Mode + list management ------------------------------------------------ */

	[[nodiscard]] std::optional<OperatingMode> getMode(Endpoint& endpoint)
	{
		std::promise<std::optional<OperatingMode>> promise;
		auto future = promise.get_future();
		endpoint.session->getOperatingMode(
			kDefaultTimeout,
			[&promise](ErrorCode code, std::string_view, std::optional<OperatingMode> mode,
					   ResponseOrigin) {
				promise.set_value(code == ErrorCode::Ok ? mode : std::nullopt);
			});
		return future.get();
	}

	void ensureMode(Endpoint& endpoint, OperatingMode target)
	{
		const auto current = getMode(endpoint);
		ASSERT_TRUE(current.has_value())
			<< "Could not read operating mode on " << endpoint.config.port;
		if (*current == target) {
			return;
		}
		if (!endpoint.savedMode.has_value()) {
			endpoint.savedMode = *current;
		}
		std::promise<ErrorCode> promise;
		auto future = promise.get_future();
		endpoint.session->setOperatingMode(
			target, kDefaultTimeout,
			[&promise](ErrorCode code, std::string_view, ResponseOrigin) {
				promise.set_value(code);
			});
		ASSERT_EQ(future.get(), ErrorCode::Ok)
			<< "Failed to switch operating mode on " << endpoint.config.port;
		std::this_thread::sleep_for(kModeChangeSettle);
	}

	/* Best-effort restore. These waits deliberately give up after the
	   timeout (a dead device must not hang TearDown), so the completion
	   state is heap-held and captured by value: a callback that fires
	   after the wait was abandoned - the SDK's timeout tick or close()'s
	   cancellation can both land later than our own deadline - writes to
	   still-live state instead of a destroyed stack promise. */
	void restoreEndpoint(Endpoint& endpoint)
	{
		if (!endpoint.session) {
			return;
		}
		const auto awaitBestEffort = [](auto issueCall) {
			auto done = std::make_shared<std::promise<void>>();
			auto future = done->get_future();
			issueCall([done](ErrorCode, std::string_view, ResponseOrigin) {
				done->set_value();
			});
			(void)future.wait_for(kDefaultTimeout);
		};
		if (endpoint.listsTouched) {
			awaitBestEffort([&](auto callback) {
				endpoint.session->defaultPgnEnableList(DeletePgnListSelector::Both,
													   kDefaultTimeout, callback);
			});
			awaitBestEffort([&](auto callback) {
				endpoint.session->activatePgnEnableLists(kDefaultTimeout, callback);
			});
		}
		if (endpoint.savedMode.has_value()) {
			awaitBestEffort([&](auto callback) {
				endpoint.session->setOperatingMode(*endpoint.savedMode, kDefaultTimeout,
												   callback);
			});
		}
	}

	/* Synchronous single-PGN enable SET + activate on either list. Returns the
	   SET's error code; activation problems are logged but non-fatal. */
	[[nodiscard]] ErrorCode setEnableAndActivate(Endpoint& endpoint, bool txList, uint32_t pgn,
												 uint8_t enable)
	{
		endpoint.listsTouched = true;
		std::promise<ErrorCode> setPromise;
		auto setFuture = setPromise.get_future();
		const auto ack = [&setPromise](ErrorCode code, std::string_view, ResponseOrigin) {
			setPromise.set_value(code);
		};
		if (txList) {
			endpoint.session->setTxPgnEnable(pgn, enable, kDefaultTimeout, ack);
		} else {
			endpoint.session->setRxPgnEnable(pgn, enable, kDefaultTimeout, ack);
		}
		const ErrorCode setCode = setFuture.get();
		if (setCode != ErrorCode::Ok) {
			return setCode;
		}

		std::promise<ErrorCode> activatePromise;
		auto activateFuture = activatePromise.get_future();
		endpoint.session->activatePgnEnableLists(
			kDefaultTimeout, [&activatePromise](ErrorCode code, std::string_view, ResponseOrigin) {
				activatePromise.set_value(code);
			});
		const ErrorCode activateCode = activateFuture.get();
		if (activateCode != ErrorCode::Ok) {
			std::cout << "    activatePgnEnableLists returned ec="
					  << static_cast<int>(activateCode) << " (continuing)" << std::endl;
		}
		std::this_thread::sleep_for(kSettleDelay);
		return ErrorCode::Ok;
	}

	/* Diagnostic: read back a PGN's enable state after a SET. Enabled with
	   ACTISENSE_TEST_READBACK=1 - answers "did the SET actually apply?" when
	   a sweep result looks wrong. */
	void readbackEnableState(Endpoint& endpoint, bool txList, uint32_t pgn)
	{
		static const bool enabled = [] {
			const char* env = std::getenv("ACTISENSE_TEST_READBACK");
			return env != nullptr && std::string(env) == "1";
		}();
		if (!enabled) {
			return;
		}
		if (txList) {
			std::promise<std::string> promise;
			auto future = promise.get_future();
			endpoint.session->getTxPgnEnable(
				pgn, kDefaultTimeout,
				[&promise](ErrorCode code, std::string_view msg,
						   std::optional<TxPgnEnableResponse> response, ResponseOrigin) {
					if (code != ErrorCode::Ok || !response.has_value()) {
						promise.set_value("GET failed: " + std::string(msg));
						return;
					}
					promise.set_value(
						"enable=" + std::to_string(static_cast<int32_t>(response->enable)) +
						" txRate=" + std::to_string(response->txRate));
				});
			std::cout << "    readback Tx " << pgn << ": " << future.get() << std::endl;
		} else {
			std::promise<std::string> promise;
			auto future = promise.get_future();
			endpoint.session->getRxPgnEnable(
				pgn, kDefaultTimeout,
				[&promise](ErrorCode code, std::string_view msg,
						   std::optional<RxPgnEnableResponse> response, ResponseOrigin) {
					if (code != ErrorCode::Ok || !response.has_value()) {
						promise.set_value("GET failed: " + std::string(msg));
						return;
					}
					char mask[16];
					std::snprintf(mask, sizeof(mask), "0x%08X", response->mask);
					promise.set_value(
						"enable=" + std::to_string(static_cast<int32_t>(response->enable)) +
						" mask=" + mask);
				});
			std::cout << "    readback Rx " << pgn << ": " << future.get() << std::endl;
		}
	}

	[[nodiscard]] ErrorCode sendPgnSync(Endpoint& endpoint, uint32_t pgn,
										std::span<const uint8_t> payload)
	{
		std::promise<ErrorCode> promise;
		auto future = promise.get_future();
		endpoint.session->sendPgn(pgn, payload, 0xFF, 6,
								  [&promise](ErrorCode code) { promise.set_value(code); });
		return future.get();
	}

	void drainFrames(Endpoint& endpoint)
	{
		std::lock_guard<std::mutex> lock(endpoint.mutex);
		endpoint.frames.clear();
	}

	/* Wait for a frame matching (pgn, payload) at @p endpoint. @p maskIndex
	   optionally names one byte excluded from comparison — the transmitter's
	   firmware-managed SID byte, when the rig says the model rewrites it. */
	[[nodiscard]] bool waitForMatch(Endpoint& endpoint, uint32_t pgn,
									std::span<const uint8_t> payload,
									std::optional<std::size_t> maskIndex,
									std::chrono::milliseconds timeout)
	{
		const auto deadline = std::chrono::steady_clock::now() + timeout;
		std::unique_lock<std::mutex> lock(endpoint.mutex);
		while (true) {
			while (!endpoint.frames.empty()) {
				CapturedFrame frame = std::move(endpoint.frames.front());
				endpoint.frames.pop_front();
				if (frame.pgn != pgn || frame.data.size() < payload.size()) {
					continue;
				}
				bool match = true;
				for (std::size_t i = 0; i < payload.size(); ++i) {
					if (maskIndex.has_value() && i == *maskIndex) {
						continue;
					}
					if (frame.data[i] != payload[i]) {
						match = false;
						break;
					}
				}
				if (match) {
					return true;
				}
			}
			if (endpoint.cv.wait_until(lock, deadline) == std::cv_status::timeout) {
				return false;
			}
		}
	}

	/* Payload + candidate helpers ------------------------------------------- */

	[[nodiscard]] std::vector<uint8_t> makePatternPayload(const PgnManifestEntry& entry,
														  std::size_t length) const
	{
		std::vector<uint8_t> payload(length);
		for (std::size_t i = 0; i < length; ++i) {
			const uint32_t mix =
				entry.pgn ^ (static_cast<uint32_t>(i) * 0x11u) ^ runSalt_;
			payload[i] = static_cast<uint8_t>(mix & 0xFFu);
		}
		/* Force the Data Instance byte to 0: gateway firmware that enforces an
		   instance match on host-Tx pre-builds its default Tx objects with
		   instance 0 and silently drops mismatches. */
		if (entry.instanceIndex != kManifestNone && entry.instanceIndex < length) {
			payload[entry.instanceIndex] = 0;
		}
		return payload;
	}

	[[nodiscard]] std::vector<PgnManifestEntry> candidates() const
	{
		const char* full = std::getenv("ACTISENSE_TEST_FULL_SWEEP");
		const bool fullSweep = (full != nullptr && std::string(full) == "1");
		/* A single-PGN focus always draws from the full candidate pool, not
		   the smoke subset — the point is to debug one specific PGN. */
		if (const char* only = std::getenv("ACTISENSE_TEST_ONLY_PGN"); only && *only) {
			const uint32_t wanted = static_cast<uint32_t>(std::strtoul(only, nullptr, 10));
			auto all = selectSweepCandidates(manifest_, /*fullSweep=*/true, kSkipPgns);
			std::vector<PgnManifestEntry> filtered;
			for (const auto& entry : all) {
				if (entry.pgn == wanted) {
					filtered.push_back(entry);
				}
			}
			return filtered;
		}
		return selectSweepCandidates(manifest_, fullSweep, kSkipPgns);
	}

	/* The transmitter's SID byte cannot be compared when its firmware rewrites
	   it. The byte index comes from the manifest; older manifest entries with
	   no SID index fall back to byte 0, the conventional SID position. */
	[[nodiscard]] static std::optional<std::size_t>
	sidMaskIndex(const RigDevice& transmitter, const PgnManifestEntry& entry)
	{
		if (!transmitter.rewritesSidByte0) {
			return std::nullopt;
		}
		if (entry.sidIndex != kManifestNone) {
			return static_cast<std::size_t>(entry.sidIndex);
		}
		return static_cast<std::size_t>(0);
	}

	/* Sweep cores ----------------------------------------------------------- */

	void runTxSweep(Endpoint& transmitter, Endpoint& monitor, const std::string& direction)
	{
		ensureMode(transmitter, OperatingMode::NgTransferNormalMode);
		ensureMode(monitor, OperatingMode::NgTransferRxAllMode);
		if (::testing::Test::HasFatalFailure()) {
			return;
		}
		runSweep(transmitter, monitor, /*toggleTx=*/true, direction);
	}

	void runRxSweep(Endpoint& transmitter, Endpoint& receiver, const std::string& direction)
	{
		ensureMode(transmitter, OperatingMode::NgTransferNormalMode);
		ensureMode(receiver, OperatingMode::NgTransferNormalMode);
		if (::testing::Test::HasFatalFailure()) {
			return;
		}
		runSweep(transmitter, receiver, /*toggleTx=*/false, direction);
	}

	/* Shared two-phase sweep. toggleTx=true toggles the transmitter's Tx list
	   (observer = transparent monitor in Rx-All); toggleTx=false keeps the
	   transmitter Tx-enabled and toggles the observer's Rx list (observer in
	   Normal mode). */
	void runSweep(Endpoint& transmitter, Endpoint& observer, bool toggleTx,
				  const std::string& direction)
	{
		const auto sweepSet = candidates();
		if (sweepSet.empty()) {
			GTEST_SKIP() << "Candidate set is empty (check the manifest and"
						 << " ACTISENSE_TEST_ONLY_PGN)";
		}
		std::cout << "  Sweeping " << sweepSet.size() << " PGN(s), direction " << direction
				  << ", " << (toggleTx ? "Tx" : "Rx") << " filter" << std::endl;

		for (const auto& entry : sweepSet) {
			SCOPED_TRACE("PGN " + std::to_string(entry.pgn) + " (" + entry.name + ")");

			SweepRecord record;
			record.pgn = entry.pgn;
			record.name = entry.name;
			record.fixture = fixture_.id;
			record.direction = direction;
			record.list = toggleTx ? "tx" : "rx";

			/* A v2-era device cannot source or list a PGN missing from its
			   library — those rows are unreachable, not filter failures. */
			if (!entry.v2Supported &&
				(transmitter.config.v2Device || observer.config.v2Device)) {
				record.verdict = Verdict::SkipV2Unsupported;
				record.note = transmitter.config.v2Device
								  ? "transmitter carries the v2-era PGN library"
								  : "observer carries the v2-era PGN library";
				records_.push_back(std::move(record));
				continue;
			}

			const auto length = payloadLengthFor(entry);
			if (!length.has_value()) {
				record.verdict = Verdict::SkipLengthUnknown;
				record.note = "no usable payload length in the manifest";
				records_.push_back(std::move(record));
				continue;
			}
			const auto payload = makePatternPayload(entry, *length);
			const auto mask = sidMaskIndex(transmitter.config, entry);
			const auto waitTimeout = entry.fast ? kRxWaitTimeoutFast : kRxWaitTimeout;
			Endpoint& toggled = toggleTx ? transmitter : observer;

			/* On the Rx sweep the transmitter must have the PGN Tx-enabled so
			   the bus actually carries it. */
			if (!toggleTx) {
				const ErrorCode txCode =
					setEnableAndActivate(transmitter, /*txList=*/true, entry.pgn, 1);
				if (txCode != ErrorCode::Ok) {
					record.verdict = Verdict::SkipSetRejected;
					record.note = "transmitter rejected the Tx-enable SET (ec=" +
								  std::to_string(static_cast<int32_t>(txCode)) + ")";
					records_.push_back(std::move(record));
					continue;
				}
			}

			/* --- Enable phase ---------------------------------------------- */
			drainFrames(observer);
			const ErrorCode enableCode =
				setEnableAndActivate(toggled, toggleTx, entry.pgn, 1);
			if (enableCode != ErrorCode::Ok) {
				record.verdict = Verdict::SkipSetRejected;
				record.note = "enable SET rejected (ec=" +
							  std::to_string(static_cast<int32_t>(enableCode)) + ")";
				records_.push_back(std::move(record));
				continue;
			}
			readbackEnableState(toggled, toggleTx, entry.pgn);
			const ErrorCode sendEnabledCode = sendPgnSync(transmitter, entry.pgn, payload);
			if (sendEnabledCode != ErrorCode::Ok) {
				record.verdict = Verdict::SkipSendRejected;
				record.note = "sendPgn rejected while enabled (ec=" +
							  std::to_string(static_cast<int32_t>(sendEnabledCode)) + ")";
				records_.push_back(std::move(record));
				continue;
			}
			const bool observedEnabled =
				waitForMatch(observer, entry.pgn, payload, mask, waitTimeout);
			record.enabledResult = observedEnabled ? "observed" : "not-observed";

			/* --- Block phase ----------------------------------------------- */
			const ErrorCode disableCode =
				setEnableAndActivate(toggled, toggleTx, entry.pgn, 0);
			if (disableCode != ErrorCode::Ok) {
				record.verdict = Verdict::SkipSetRejected;
				record.note = "disable SET rejected (ec=" +
							  std::to_string(static_cast<int32_t>(disableCode)) + ")";
				records_.push_back(std::move(record));
				continue;
			}
			readbackEnableState(toggled, toggleTx, entry.pgn);
			drainFrames(observer);
			const ErrorCode sendBlockedCode = sendPgnSync(transmitter, entry.pgn, payload);
			if (sendBlockedCode != ErrorCode::Ok) {
				record.verdict = Verdict::SkipSendRejected;
				record.note = "sendPgn rejected while disabled (ec=" +
							  std::to_string(static_cast<int32_t>(sendBlockedCode)) + ")";
				records_.push_back(std::move(record));
				continue;
			}
			const bool observedBlocked =
				waitForMatch(observer, entry.pgn, payload, mask, waitTimeout);
			record.blockedResult = observedBlocked ? "observed" : "not-observed";

			/* --- Classification -------------------------------------------- */
			record.verdict = classifyTwoPhase(observedEnabled, observedBlocked);

			EXPECT_NE(record.verdict, Verdict::FailLeak)
				<< "PGN " << entry.pgn << " (" << entry.name << ") observed at the"
				<< " observer while disabled - the " << record.list
				<< " enable filter leaked";
			EXPECT_NE(record.verdict, Verdict::FailNoTx)
				<< "PGN " << entry.pgn << " (" << entry.name << ") was not observed"
				<< " while enabled - transmit path failure (or the PGN cannot"
				<< " traverse this fixture)";

			records_.push_back(std::move(record));
		}
	}

	void printSummary() const
	{
		if (records_.empty()) {
			return;
		}
		std::size_t pass = 0;
		std::size_t leak = 0;
		std::size_t noTx = 0;
		std::size_t skip = 0;
		for (const auto& record : records_) {
			switch (record.verdict) {
				case Verdict::Pass: ++pass; break;
				case Verdict::FailLeak: ++leak; break;
				case Verdict::FailNoTx: ++noTx; break;
				default: ++skip; break;
			}
		}
		std::cout << "  Sweep summary: " << pass << " pass, " << leak << " leak, "
				  << noTx << " no-tx, " << skip << " skipped ("
				  << records_.size() << " records)" << std::endl;
		for (const auto& record : records_) {
			if (record.verdict != Verdict::Pass) {
				std::cout << "    " << record.pgn << " " << record.name << " ["
						  << record.direction << "/" << record.list << "] "
						  << verdictToString(record.verdict)
						  << (record.note.empty() ? "" : (" - " + record.note))
						  << std::endl;
			}
		}
	}
};

/* ========================================================================== */
/* The four sweep passes                                                      */
/* ========================================================================== */

TEST_F(PgnEnableSweepTest, TxFilterSweepAToB)
{
	runTxSweep(endpointA_, endpointB_, "a_to_b");
}

TEST_F(PgnEnableSweepTest, TxFilterSweepBToA)
{
	runTxSweep(endpointB_, endpointA_, "b_to_a");
}

TEST_F(PgnEnableSweepTest, RxFilterSweepAToB)
{
	runRxSweep(endpointA_, endpointB_, "a_to_b");
}

TEST_F(PgnEnableSweepTest, RxFilterSweepBToA)
{
	runRxSweep(endpointB_, endpointA_, "b_to_a");
}

} /* namespace Test */
} /* namespace Sdk */
} /* namespace Actisense */

/**************** (C) COPYRIGHT Active Research Limited  ** END OF FILE **/
